#!/usr/bin/env bash
# Regenerates the Xcode project and builds the Debug app into .build/xcode.
set -euo pipefail
cd "$(dirname "$0")/.."

plist=App/GoogleService-Info.plist
if [[ ! -f $plist ]]; then
  echo "Missing $plist: download it from the Firebase console (Apple app dev.kortex.mac)." >&2
  exit 1
fi
reversed=$(/usr/libexec/PlistBuddy -c "Print :REVERSED_CLIENT_ID" "$plist")
printf '// Generated by scripts/build.sh from %s. Do not edit.\nGOOGLE_REVERSED_CLIENT_ID = %s\n' "$plist" "$reversed" > App/Generated.xcconfig

xcodegen --quiet
args=(-project Kortex.xcodeproj -scheme Kortex -configuration Debug
      -destination 'platform=macOS,arch=arm64' -derivedDataPath .build/xcode
      -allowProvisioningUpdates build)
if command -v xcbeautify >/dev/null; then
  xcodebuild "${args[@]}" | xcbeautify
else
  xcodebuild -quiet "${args[@]}"
fi
